spring:
 profiles:
  active: dev
 application:
  name: currency-conversion-service
  
Server:
 port: 8100  
--- 
spring:
 jpa:
  hibernate:
   ddl-auto: none
 h2:
  console:
   enabled: true 
   path: /h2    
---
 spring:
  profiles: dev 
  
---  
eureka:
 client:
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
  preferIpAddress: true 
--- 
 

  
   